#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"
#include "vecmat.h"

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include <wx/filedlg.h>
#include <wx/wfstream.h>
#include <wx/log.h> 
#include <wx/wx.h>
#include <wx/event.h>
#include <wx/dcmemory.h>

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void OpenFile( wxCommandEvent& event );
		void Revert( wxCommandEvent& event );
		void Recount_Axes( wxScrollEvent& event );
		void Change_Angle( wxScrollEvent& event );
		void Move_X( wxScrollEvent& event );
		void Move_Y( wxScrollEvent& event );
		void Interpolate( wxCommandEvent& event );
		void SaveFile( wxCommandEvent& event );
		void Animate( wxCommandEvent& event );
		void Resize(wxSizeEvent& event);

		void Repaint();
		void Reflect(int angle);
		void Extend();
		void CreateMask(int width, int height);

		wxImage NearestNeighborInterpolation(const wxImage& inputImage, int newWidth, int newHeight);
		wxImage BilinearInterpolation(const wxImage& image, float newWidth, float newHeight);

		wxImage original;
		wxImage shifted;
		wxImage copy;

		wxImage mask;
		wxImage extended;

		int test_var;
		double axes_angle;
		int axes_count;
		double angle;
		int curr_x, curr_y;
		int interpol;
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

};
#endif // __GUIMyFrame1__
