#ifndef __GUIMyFrame1__
#define __GUIMyFrame1__

/**
@file
Subclass of MyFrame1, which is generated by wxFormBuilder.
*/

#include "GUI.h"

#include <wx/filedlg.h>
#include <wx/dcmemory.h>
#include <wx/dcclient.h>
#include <wx/dcbuffer.h>
#include <wx/colourdata.h>
#include <wx/colordlg.h>
#include <wx/filedlg.h>
#include <wx/wfstream.h>
#include <wx/log.h> 


#include <opencv2/core.hpp>
#include <opencv2/imgcodecs.hpp>
#include <opencv2/core/mat.hpp>

//// end generated include

/** Implementing MyFrame1 */
class GUIMyFrame1 : public MyFrame1
{
	protected:
		// Handlers for MyFrame1 events.
		void OpenFile( wxCommandEvent& event );
		void Revert( wxCommandEvent& event );
		void Recount_Axes( wxScrollEvent& event );
		void Change_Angle( wxScrollEvent& event );
		void Move_X( wxScrollEvent& event );
		void Move_Y( wxScrollEvent& event );
		void Interpolate( wxCommandEvent& event );
		void SaveFile( wxCommandEvent& event );
		void whateverthisis( wxCommandEvent& event );

		void Repaint();

		wxImage original;
		wxImage copy;
	public:
		/** Constructor */
		GUIMyFrame1( wxWindow* parent );
	//// end generated class members

};

#endif // __GUIMyFrame1__
